name: GitHub CI

on:
  push:
    tags:
      - v*
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Install
        run: npm install
      - name: Test
        run: npm test
